### ISSUE TITLE
HTTPS POST is failing with certificate error

### ISSUE THREAD

**Issue by irfanazam1** [spluxx/Protoman#25]
I am trying to do a POST on an HTTPS address but getting the following error whereas the certificate has been imported into the ca-trusts as well in the browser.

 failed, reason: self signed certificate in certificate chain

Kindly let me know if there is way to bypass certificate validation or where to import the certificate to resolve the issue.

Operating system: CentOS 7

**Comment by spluxx** [comment]
https://github.com/node-fetch/node-fetch/issues/19#issuecomment-289709519

It's a quick (and kinda unsafe) workaround, but I think it'll do. What do you think? I'll work on it next week.

**Comment by irfanazam1** [comment]
This is what I did and recompiled to make it working. It is unsafe but the tool is mostly used during dev/testing, so safety won't matter much.

**Comment by spluxx** [comment]
Nice. I'll address this on the next version. Thank you!

**Comment by wgithu** [comment]
Hi. When you have time, would you release a version with the fix for issue #25 in order to bypass certificate verification?

**Comment by irfanazam1** [comment]
Sure, I will do that. I will try to send you a PR by mid next week.

**Comment by dscmbvnc** [comment]
Hello. Will there be a new build with fix for issue #25 please?

**Comment by irfanazam1** [comment]
Hi,

Sorry for the late reply. Actually, I was moving my house in the last few
weeks and still getting settled. I will be able to start looking into stuff
by the end or early next week. Sorry for not looking into this sooner.

Regards,
Irfan

**Comment by karan6190** [comment]
Hi team, is issue https://github.com/spluxx/Protoman/issues/25 resolved?

**Comment by vorte** [comment]
I've just raised a pr ^ which should resolve this issue. We just need to get it merged and released
