### ISSUE TITLE
More flexible export for a collection

### ISSUE THREAD

**Issue by igor-drozdov-n26** [spluxx/Protoman#32]
For now when I export a collection, paths to proto files most probably will not work on other machines as its are absolute paths on a machine where I create them.

For example:
```
"protoFilepaths": [
    "<absolute_path>"
],
```

I would like to not rely on local path and possible solutions I see for that:

1. Ability to point to a file accessible via `http`
2. During export add all files to export

On top of that I can suggest attacking the problem from a different point:
Now I need to export all files one by one but probably it makes sense to export the whole directory and Protoman can recursively find all proto definition. In that case other people can (only once) just point to the directory with definitions and other future changes will not require from them to export new files.

Or instead of directory maybe it's possible to add a jar dependency

**Comment by spluxx** [comment]
> Now I need to export all files one by one but probably it makes sense to export the whole directory and Protoman can recursively find all proto definition. In that case other people can (only once) just point to the directory with definitions and other future changes will not require from them to export new files.

I think this point is similar to #16, except pointing to a file via http isn't something I've thought about. Do you think #16 may be sufficient for your usecase?

**Comment by igor-drozdov-n26** [comment]
Yeah, I think it solves most of my use-cases 👍
