### ISSUE TITLE
Large int64 values are truncated

### ISSUE THREAD

**Issue by yesthatguy** [spluxx/Protoman#39]
I have a `locationId` field in my proto which is a fixed64 type, and am trying to request location ID 1234577704719498930

The server is instead receiving a request for location ID 1234577704719499008

Having run into this with some web frontends, my best guess is that Protoman is using a javascript Number internally, which only supports 53 bits, so it's truncating the integer input. This can probably be fixed by using [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) instead of Number.

**Comment by pandawithcat** [comment]
thanks for the feedback. I've been MIA for a while but now i'm back on track so i'll try to resolve most of the issues soon!

**Comment by DonghunLouisLee** [comment]
@yesthatguy  fixed64 is an ongoing issue for protobuf.js(https://github.com/protobufjs/protobuf.js/pull/1557) and since protoman relies on protobuf.js, this issue will be handled when protobuf.js is handled!
