### ISSUE TITLE
The given content-type is unsupported.

### ISSUE THREAD

**Issue by bryanhughes** [spluxx/Protoman#46]
Hello, I am returning a content-type `application/x-protobuf` but getting content-type is unsupported. Which content-type does Protoman expect? The Request correctly serializes the protobuffer from the managed collection.

Thanks

**Comment by Hitesh-Kirtane** [comment]
**Hi Development Team,**

I am also getting the same error. Even after passing content-type as "application/x-protobuf", it is giving the error "given content type is unsupported" message in response.

I have added a screenshot below for your perusal.

Request you to please provide a solution for this issue.

![image](https://user-images.githubusercontent.com/39984502/111299424-eec33c00-8675-11eb-985d-dbe06e650709.png)

Thanks.

**Comment by david-buck** [comment]
You may need to put `"application/x-protobuf"` in quotes.

![image](https://user-images.githubusercontent.com/5119820/111595802-5ffb1e80-8831-11eb-8082-2ddc851d22ca.png)

This fixed it for me

**Comment by moonshine-fish** [comment]
Hi guys, have you checked your **Expected Message** configs? You should assign which type of protobuf message to be used when parsing your protobuf response.
![image](https://user-images.githubusercontent.com/15911445/112301872-5e1fd800-8cd5-11eb-9488-4275abbb70c4.png)

**Comment by bryanhughes** [comment]
Sorry fo the late reply. Been swamped at the day job. I hope to test this out this evening. Cheers

**Comment by VickyZhangjh** [comment]
I am also getting the same error.

**Comment by Tawenxd** [comment]
I am also getting the same error. Even after passing content-type as "application/x-protobuf", it is giving the error "given content type is unsupported" message in response.

**Comment by Tawenxd** [comment]
I am also getting the same error. Even after passing content-type as "application/x-protobuf", it is giving the error "given content type is unsupported" message in response.
![image](https://user-images.githubusercontent.com/19664829/113255116-0814eb00-92fa-11eb-9f29-ade2b506b63e.png)

**Comment by Hitesh-Kirtane** [comment]
**Hi Team**,

This issue is resolved.

Actually, the solution is simple.

Just we have to load the .proto files in the collection by right-clicking on the API collection and we have to build it, that's it.

Now we can try hitting the endpoint. Do remember to add headers as below.

Accept - application/x-protobuf
content-type - application/x-protobuf

Please refer the [Readme file here](https://github.com/spluxx/Protoman/blob/master/README.md) for detailed steps about this setup.

**Note:** You must have .proto files (for request and response) in order to hit the protobuf supported endpoint.

Hope this helps.

Thanks.

**Comment by pandawithcat** [comment]
@Hitesh-Kirtane  thanks for helping out! Would it be okay to close this issue?

**Comment by Hitesh-Kirtane** [comment]
@pandawithcat - Sure, you may close this issue. All, please confirm.

**Comment by ahezzati** [comment]
> **Hi Team**,
> 
> This issue is resolved.
> 
> Actually, the solution is simple.
> 
> Just we have to load the .proto files in the collection by right-clicking on the API collection and we have to build it, that's it.
> 
> Now we can try hitting the endpoint. Do remember to add headers as below.
> 
> Accept - application/x-protobuf
> content-type - application/x-protobuf
> 
> Please refer the [Readme file here](https://github.com/spluxx/Protoman/blob/master/README.md) for detailed steps about this setup.
> 
> **Note:** You must have .proto files (for request and response) in order to hit the protobuf supported endpoint.
> 
> Hope this helps.
> 
> Thanks.

Thanks @Hitesh-Kirtane  for your response but what if the response type is not protobuf? what if I want to return text/plain or application/json how can I configure Protoman to handle this?

**Comment by Hitesh-Kirtane** [comment]
> > **Hi Team**,
> > This issue is resolved.
> > Actually, the solution is simple.
> > Just we have to load the .proto files in the collection by right-clicking on the API collection and we have to build it, that's it.
> > Now we can try hitting the endpoint. Do remember to add headers as below.
> > Accept - application/x-protobuf
> > content-type - application/x-protobuf
> > Please refer the [Readme file here](https://github.com/spluxx/Protoman/blob/master/README.md) for detailed steps about this setup.
> > **Note:** You must have .proto files (for request and response) in order to hit the protobuf supported endpoint.
> > Hope this helps.
> > Thanks.
> 
> Thanks @Hitesh-Kirtane for your response but what if the response type is not protobuf? what if I want to return text/plain or application/json how can I configure Protoman to handle this?

Hi @ahezzati,

I guess as of now, Protoman only supports request and response structures in protobuf format.

We might see support for content types such as text/plain and application/json in nearby future.

There are some open issues created for requesting support of application/json content type in Protoman (GH-48 and GH-56).

You may check these out for more information.

Thanks.
