### ISSUE TITLE
The request url bar is truncated when I increase the window size on MacOS

### ISSUE THREAD

**Issue by thibaut-pro** [spluxx/Protoman#58]
Screenshot for context:
![image](https://user-images.githubusercontent.com/59576766/122096728-b4c41c00-cdc3-11eb-952f-6d66aa8643b1.png)

I love this tool! Thanks a lot for building it.

**Comment by arturwwl** [comment]
duplicate of #41

**Comment by DonghunLouisLee** [comment]
will fix in the next version
