### ISSUE TITLE
synchronization and cloud?

### ISSUE THREAD

**Issue by abner-xu** [spluxx/Protoman#6]
Whether to support interface synchronization, multi-platform cloud support

**Comment by spluxx** [comment]
Hey! Thanks for the issue. Could you elaborate on the interface synchronization part?

**Comment by abner-xu** [comment]
For example, cloud backup or multiple device synchronization requests

**Comment by spluxx** [comment]
Sounds good. We'll be providing that functionality in some way or another. Perhaps exporting the collection as a JSON, as that wouldn't require us to host a separate server for it.

**Comment by spluxx** [comment]
#11
